version: "3.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  nextdns:
    container_name: nextdns
    ports:
      - 8053:8053/udp
      - 8053:8053/tcp
    build:
      context: ./nextdns
    environment:
      NEXTDNS_ID: 'cfaa54'
      TZ: 'Europe/Paris'
    networks:
      cyber:
        ipv4_address: 10.98.0.98
    healthcheck:
      test: ["CMD", "drill", "-p", "8053", "cloudflare.com", "@10.98.0.98", "||", "exit", "1"]
      interval: 20s
      timeout: 20s
      retries: 3
      start_period: 5s
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'pouet'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    networks:
      cyber:
        ipv4_address: 10.98.0.99
      # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    depends_on:
      - nextdns
    restart: unless-stopped
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      #- SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - pihole
    networks:
      cyber:
    #   ipv4_address: 10.0.0.1
networks:
  cyber:
    ipam:
      driver: default
      config:
        - subnet: "10.98.0.0/24"
